close all; clear all; clc;

% We open an image file, convert it to grayscale and generate a binary file

IM = rgb2gray(imread('dolphin.jpg')); % droid.png: 500x500 image
% IM range: [0 to 255]

% Generating binary files for hardware processing
  filename_out = strcat('dolphin.bif');
  [n, m] = size (IM); % n: # of rows, m: # of columns

% Data is reordered linearly in a raster scan fashion  
  Braster = reshape (IM',1,n*m); % elements are taken column-wise from input matrix IM'
                             % Here, elements re taken row-wise from input matrix IM
  
% Creating a binary file with .bif (binary image file) extension
  fid = fopen(filename_out, 'w');
  fwrite(fid, Braster, 'uint8');
  fclose (fid);

% Displaying input and output figures:
% ***********************************
% This requires the output file 'droid.bof' generated by the embedded system.
  figure; imshow (IM); % Input image
  
% Reading output binary file:
  fad = fopen ('dolphin.bof','r');
  odata = fread (fad, n*m, 'uint8=>uint8');
  fclose (fad);
  oimg = reshape(odata, n, m); % data is taken colum-wise, but we wanted it row-wise, then oimg'
  figure; imshow(oimg');