#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "xil_cache.h"
#include "xparameters.h"
#include "xfilter2d_accel_opt.h"         // Auto-generated by Vitis HLS export
#include "ff.h"               // Xilinx FatFs for SD card access
#include "platform.h"
#include "xil_printf.h"
#include "xiltimer.h"

// Kernels
 
static const char kernel_sharpen[9] = {
     0, -1,  0,
    -1,  5, -1,
     0, -1,  0
};
 
static const char kernel_edge[9] = {
    -1, -1, -1,
    -1,  8, -1,
    -1, -1, -1
};
 
static const char kernel_identity[9] = {
    0, 0, 0,
    0, 1, 0,
    0, 0, 0
};

int fileRead(u8* input);
int fileWrite(u8* output);
FRESULT timePrint();
void filter2d_SW(u8* img_in,char* kernel, u8* img_out, int rows, int cols);